import { Telegraf } from "telegraf";
import fetch from "node-fetch";
import dotenv from "dotenv";

dotenv.config();

const bot = new Telegraf(process.env.TELEGRAM_BOT_TOKEN);
const BACKEND = process.env.BACKEND_URL;

bot.start((ctx) => {
  ctx.reply(
    "🎨 NeuroArt Bot\n\nUse:\n/imagine your prompt\nExample:\n/imagine cyberpunk city in rain"
  );
});

bot.command("imagine", async (ctx) => {
  const prompt = ctx.message.text.replace("/imagine", "").trim();

  if (!prompt) {
    return ctx.reply("Please provide a prompt.");
  }

  await ctx.reply("Generating image…");

  try {
    const res = await fetch(`${BACKEND}/api/generate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ prompt, aspectRatio: "1:1" })
    });

    const data = await res.json();

    if (!data.success) {
      return ctx.reply(data.error || "Failed.");
    }

    await ctx.replyWithPhoto(data.imageUrl, {
      caption: `✨ ${prompt}\nGenerated by NeuroArt`
    });
  } catch (err) {
    console.error(err);
    ctx.reply("Error generating image.");
  }
});

bot.launch();
console.log("Telegram bot running");

process.once("SIGINT", () => bot.stop());
process.once("SIGTERM", () => bot.stop());
